questionary/prompts/common.py
tests/prompts/test_common.py

Changes:
- support Validator instances (useful if the Validator was created with `Validator.from_callable`)

add support for 'Validator' instances

---

README.md
questionary/prompts/common.py
tests/prompts/test_common.py

Enable pointer and highlighted text to coexist

---

MANIFEST.in
setup.py

Include docs, examples and tests

MANIFEST.in: Update

---

.travis.yml
questionary/prompts/autocomplete.py
questionary/question.py
questionary/utils.py
requirements.txt
setup.py
tests/prompts/test_autocomplete.py
tests/utils.py

- added support for prompt_toolkit 3
- run tests on both, prompt_toolkit 2 and 3
- removed support for python 3.5 (prompt_toolkit 3 does not support that anymore)
fixes #31

Support for prompt toolkit 3

---

.travis.yml
questionary/prompts/autocomplete.py
questionary/prompts/confirm.py
questionary/prompts/password.py
questionary/prompts/rawselect.py
questionary/prompts/text.py
requirements_dev.txt

Fixed #45 (colour of answer for some prompts)

---

questionary/prompts/autocomplete.py

Had a problem supplying my own Completer, as I had to make a dummy list with a single value to get the check to pass. This commit should let people be able to supply **either** a completer **or** choices for the default completer.

Removed check for choices if completer is present

---

.github/workflows/continous-integration.yml

The tests would only run on 3.7.

Install Python version from matrix

---

questionary/prompts/confirm.py
tests/prompts/test_confirm.py

Added auto_enter parameter to confirm

---

questionary/constants.py
questionary/prompts/checkbox.py
questionary/prompts/common.py
questionary/prompts/rawselect.py
questionary/prompts/select.py

related to #103 
(squash will be done when validation complete)

WIP: add pointer option

---

pyproject.toml

Closes https://github.com/tmbo/questionary/issues/109.

Relax Python version constraint

---

questionary/constants.py

change Multi-Line instruction to Esc then Enter
Closes #114.

Change Multi-Line instruction to Esc then Enter

---

questionary/prompts/common.py

Clarify documentation for `value` argument of `Choice`

---

.github/dependabot.yml

- Fixes incorrect dependabot file name.
- Sets frequency to daily rather than weekly.

Fix incorrect dependabot file name

---

.github/workflows/continous-integration.yml

May want to add these as required checks.

Add CI tests for macOS

---

.github/workflows/continous-integration.yml

There are some errors in #139. These should be resolved by this PR.

Fix `setup-poetry` upgrade issues

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/question.yml
.github/PULL_REQUEST_TEMPLATE.md

Added issue templates to help users when asking questions, reporting bugs and requesting features.
Also added a template for PRs to assist with reviewing.

Added issue and pull request templates

---

questionary/prompt.py

supersedes #172
Closes https://github.com/tmbo/questionary/issues/112

Change-processing-order

---

Makefile
docs/pages/contributors.rst

Clarify contributors guide and help new contributors to join easier
update make file and instructions
now poetry and pre-commit are configured and installed by `make develop`. Then, every git commit automatic lint check will run ensuring code quality
**Checklist**

Add `develop` Makefile target and update contributor's guide

---

.devcontainer/devcontainer.json
Makefile
poetry.lock
pyproject.toml
setup.cfg

remove redundant `pycodestyle` as this is handled by flake which is a way more powerful
removed dev dependency 
**Checklist**

remove pycodestyle

---

.github/workflows/continous-integration.yml
tests/prompts/test_common.py
tests/test_examples.py
tests/test_form.py
tests/test_question.py
tests/utils.py

there are some breaking changes in prompt-toolkit, see https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/CHANGELOG
`questionary` handles it well except tests part
fix tests for different versions
add CI matrix
**Checklist**

Fix tests for different versions of `prompt-toolkit`

---

Makefile

A change made in #270 introduced a bug to the `Makefile`.
I changed the `Makefile` to use the new `--with=docs` argument.
**Checklist**

Fix bug in Makefile introduced in #270

---

.readthedocs.yml

Fixes breaking documentation build.
Closes #317.
Updated `.readthedocs.yml` to version 2, which also allows Poetry to be used for dependency installation.
**Checklist**

Update `.readthedocs.yml` to version 2

---

examples/autocomplete_ants.py
questionary/prompts/autocomplete.py

Just a very minor typo fix in a few files.
...
...
**Checklist**

Minor Typo Fix in questionary-autocomplete

---

.github/workflows/continuous-integration.yml
pyproject.toml

- Explicitly support Python 3.12 in pyproject.toml.
- Use Python 3.12 in github actions
- add Python 3.12 to test matrix.
- add Python 3.12 to black target.
...
**Checklist**

Explicitly support Python 3.12
