tmbo/questionary

- examples/rawselect.py
- examples/select.py
- examples/text.py
I was walking through the examples and found out some of the `AVAILABLE_PROMPTS` had some name changes.
> found some name changes in the examples

- questionary/prompts/select.py
- tests/prompts/test_select.py
When you leave your choices empty (aka `choices=[]`), the program crashes and some funky stuff happens.
This prevents that :)
Right now it just raises the ValueError, but I was looking for the correct place to catch the exception and output a human-readable message like you do for the other exceptions, but couldn't find it.
If you could point me in the right direction, that'd be great.
> Raise ValueError when no choices are provided in select prompt.

- questionary/prompts/password.py
- questionary/prompts/text.py
It looks like #8 did not cover everything. This removes _all_ annotations that directly use the `Type` class to allow 3.5.2 to use questionary. Closes #15
> Remove all use of Type annotation to work around 3.5.2 bug

- README.md
- examples/__init__.py
- questionary/prompts/checkbox.py
- questionary/prompts/common.py
- questionary/prompts/select.py
- tests/prompts/test_checkbox.py
- tests/prompts/test_select.py
This PR adds a several new methods of styling the `select` and `checkbox` prompts
* Add flag to disable drawing of the pointer character
* Add `highlighted` token to style the choice being pointed to
* This style will only be applied when `use_pointer` is `False`
* Add `text` token to style ordinary text
* Add `disabled` token to style disabled choices
* Disabled value is no longer displayed if it is a `bool`
* Choice titles can now be a `list` of token tuples to support custom styling
* The answer displayed after the prompt is closed will use the `answer` token
* This type of styling means that `selected` and `highlighted` tokens will have no effect
I originally thought that `use_indicator` would serve the same purpose as `use_pointer` in this PR, but for `select` it turns on the …
> Add additional styling

- questionary/prompts/common.py
This gives priority to 'selected' styling over
'highlighted' when both are applicable.
> Increase visibility of selected items in checkboxes

- .travis.yml
- README.md
- requirements_dev.txt
- setup.cfg
- setup.py
I think dev requirements need an urgent update as they are quite outdated.
The versions pinned in requirements_dev.txt do not work on more recent versions of python (3.8).
Also - you seem to run black (there is a configuration, and commits mentioning "black" not long ago - so it would be good to mention that to Contributors too - ensuring you get the pull-request already "blackified".
In addition to this, i'd propose to set something like [dependabot](https://dependabot.com/) up for this repository, to keep dependencies uptodate.
This however requires the repo owner - as it'll need to be added to the repository.
It can be configured to only update once every week or so, keeping "random noise" to a minimum.
* run tests additionally with python 3.8
* update dev-dependencies
* add mention of …
> Update dev requirements

- README.md
- examples/advanced_workflow.py
- questionary/prompt.py
As said in #34, the documentation lacks examples for advanced workflows, so this aims to provide some (for sure not complete ...).
I've also added a working example workflow - but only as dictionary configuration (`ask_dictstyle()`) for now.
Mainly because I'm not certain if this workflow style would also work for the pystyle calling possibilities without adding an if-statement and calling the questions one by one (as done in `examples/readme.py`).
The disadvantage this "one by one" calling (as done in `examples/readme.py` ) is that a user cannot easily interrupt the process with ctrl+c - but has to do that for every following question.
With the dict-style (and calling prompt only once), one interrupt will return the user immediately, no matter how many questions would still be left.
> Enhance documentation regarding advanced workflows

- MANIFEST.in
- setup.py
Questionary has type annotations but in the
absence of `py.typed` the annotations might be
ignored or the types incorrectly inferred
by type checkers.
> Add py.typed marker file

- .travis.yml
- questionary/constants.py
- questionary/prompts/text.py
- tests/test_question.py
- tests/utils.py
For devs, this feature, that was already working, is now documented.
For users, a default instruction text appears when using multiline mode.
Fix #54.
> Document multiline input for devs and users

- questionary/prompts/common.py
Passing a style tuple would produce a type error because `title` was
annotated to only take strings.
> Accept style tuples in `title` argument annotation of `Choice`

- .travis.yml
- questionary/prompts/autocomplete.py
- questionary/prompts/common.py
- requirements_dev.txt
- setup.cfg
Added mypy to validate type in CI. missing stubs for promp_toolkit will be ignored.
- fixes #61
> Added mypy type checking

- questionary/constants.py
This feels more natural because multiline prompts usually start at the beginning of the terminal somehow. In a long question, the answer could start too far in the right side, and next lines too.
Of course, it can be overriden with the `instruction` parameter of the `text` prompt, so I'm just supplying a saner default.
> Indicate the multiline input with \n>

- questionary/prompts/text.py
I want to use pygments lexers when asking i.e. for YAML or JSON input.
If doing it right now, I get this error:
```
Traceback (most recent call last):
File "/var/home/yajo/prodevel/copier/.venv/bin/copier", line 5, in <module>
CopierApp.run()
File "/var/home/yajo/prodevel/copier/.venv/lib/python3.8/site-packages/plumbum/cli/application.py", line 577, in run
inst, retcode = subapp.run(argv, exit=False)
File "/var/home/yajo/prodevel/copier/.venv/lib/python3.8/site-packages/plumbum/cli/application.py", line 572, in run
retcode = inst.main(*tailargs)
File "/var/home/yajo/prodevel/copier/copier/cli.py", line 38, in _wrapper
return method(*args, **kwargs)
File "/var/home/yajo/prodevel/copier/copier/cli.py", line 262, in main
self.parent._copy(
File …
```
> Allow passing in a custom lexer

- .github/workflows/continous-integration.yml
- pyproject.toml
Using this new version specifier is equivalent to `>=3.6,<4.0.0`, which allows other projects using this same specifier work with yours.
I have this in my project, and when trying to add the master commit from questionary, poetry fails (correctly) with:
```
SolverProblemError
The current project's Python requirement (>=3.6.1,<4.0.0) is not compatible with some of the required packages Python requirement:
- questionary requires Python >=3.6,<3.9, so it will not be satisfied for Python >=3.9,<4.0.0
Because copier depends on questionary (1.6.0 git rev text-custom-lexer) which requires Python >=3.6,<3.9, version solving failed.
at ~/.local/pipx/venvs/poetry/lib64/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
237│             packages = result.packages
238│         except …
```
> Less restrictive python 3 dependency

- questionary/prompt.py
This allows to use a generator for `questions` because:
```python
>>> from typing import *
>>> issubclass(List, Iterable)
True
>>> issubclass(Generator, Iterable)
True
>>> issubclass(Generator, List)
False
```
Also allows to use other mappings, such as `collections.ChainMap`, for `answers`, because:
```python
>>> issubclass(ChainMap, Mapping)
True
>>> issubclass(Dict, Mapping)
True
>>> issubclass(ChainMap, Dict)
False
```
> Use more agnostic interface types

- questionary/prompts/common.py
- questionary/prompts/rawselect.py
- questionary/prompts/select.py
- tests/prompts/test_select.py
I needed shortcuts and arrow key item selection at the same time.
This small patch allows to do so by setting select(use_arrow_keys=True, use_shortcuts=True). Backwards compatible and not touching default behaviour (hopefully).
> Use arrow keys and shortcuts simultaneously

- examples/checkbox_toppings.py
- questionary/prompts/checkbox.py
- questionary/prompts/common.py
- tests/prompts/test_checkbox.py
I've added validation to the checkbox prompt.
`prompt-toolkit` does not provide native validation for `FormattedTextControl` (the parent class of `InquirerControl`). Therefore while `text` prompts support validators in the form of a `Validator` subclass, this only accepts a `callable` returning a boolean and optional error message. This restriction means asynchronous validators supported by `prompt-toolkit` cannot be used for the checkbox.
If/when `prompt-toolkit` provides native validation for a `FormattedTextControl`, this validation logic for the checkbox can be replaced.
Even with its limitations, I think this covers the fast majority of use cases for checkbox validation - it should be useful to some people.
> Added validation for checkboxes

- questionary/prompts/checkbox.py
- questionary/prompts/confirm.py
- questionary/prompts/select.py
At the moment, there are two spaces printed between a message and the instructions (Y/n) or answer in a `confirm dialog`.  This PR removes one of those spaces.
If the double spaces are intentional, feel free to close.
> Fix double space between question and instructions in `confirm`

- examples/checkbox_toppings.py
- questionary/constants.py
- questionary/prompts/checkbox.py
- questionary/prompts/common.py
- tests/prompts/test_checkbox.py
- tests/prompts/test_common.py
In #48 I added validation for checkboxes. I didn't realise until writing documentation that this API is not consistent with the function validation for other prompts (although having re-read the comments in the initial review, I think @tmbo did notice!). This PR makes validation for checkboxes consistent with other prompts (when using a function validator).
> Change checkbox validation API to match other prompts

- README.md
The images in the README on PyPi are broken: https://pypi.org/project/questionary/
Using direct URLs should fix this.
> Use direct image URLs in README so that they show on PyPi

- pyproject.toml
These were being included in the wheel and ultimately installed
in `site-packages` by pip, i.e. Poetry's readme and license would reside
in `site-packages/{LICENSE,README.md}.  To limit includes to the sdist
you would have to use the belatedly documented table format:
https://github.com/python-poetry/poetry/pull/2268/files.
However, the readme and the license are included by Poetry in the sdist
by default, and py.typed is included both in the wheel and the sdist
by default.  The include directive here is redundant.
> Remove Poetry includes

- tests/prompts/test_checkbox.py
- tests/prompts/test_select.py
- Test when a `Choice` instance is passed as `default` or `initial_choice`.
- Test when a `Choice` instance and string have the same value and `default` or `initial_choice` is set to the `Choice` instance.
Adding these to catch some of the breaking changes that would be introduced by #130.
> Add additional tests to `select` and `checkbox`

- questionary/prompts/common.py
issue #132 mentions an error in the highlighting of select type questions.
This error occurs when the default value is an object of type Choice because the condition being evaluated does not make a good comparison to know which option to highlight.
this is a quick, simple and functional fix that does not affect the rest of the operation.
> Fix highlighting in the questions of type select.

- .github/workflows/continous-integration.yml
Coveralls tests usually fail when new PRs are submitted (it says the coverage has decreased).
I think this is because two coverage reports are being uploaded (one for Prompt Toolkit v2 and v3) without the `COVERALLS_PARALLEL` flag being set.
This PR uploads all coverage reports and indicates to Coveralls that they should be merged.
@tmbo I think the following check should also be added as required when this is merged: https://github.com/tmbo/questionary/pull/158/checks?check_run_id=3395118300
> Fix failing Coveralls CI

- Makefile
Without this, the `make docs` command does not work.
> Fix incorrect install target in Makefile

- questionary/prompt.py
Without this patch, when calling `prompt` or `unsafe_prompt` with a `dict` on `questions`, mypy fails with:
Argument 1 to "unsafe_prompt" has incompatible type "Dict[str, Any]"; expected "Iterable[Mapping[str, Any]]"
As dict is a valid supported input, I added it to the typing information, joined within an `Union` type.
**Checklist**
> fix(types): declare support for single questions

- questionary/question.py
- tests/test_form.py
- tests/test_question.py
Two situations I tried to use today were having questions set up in a `form` where some of those questions could be skipped, and setting up my own `KeyboardInterrupt` and so needing to use `unsafe_ask`, again with questions that could be skipped.
In both of those instances, the questions would not skip.
In the `questions.py` the check for skipping:
```python
if self.should_skip_question:
return self.default
```
was in the `ask` and `ask_async` functions.  I moved this check to the `unsafe_ask` and `unsafe_ask_async` functions instead.
This has the effect of fixing the issue when trying to implement a `KeyboardInterrupt` handler (so needing to use the `unsafe_*` functions), but also allowing skipping in the `form` …
> Question skip fix

- .readthedocs.yml
- docs/conf.py
- docs/pages/api_reference.rst
- docs/requirements.txt
- poetry.lock
- pyproject.toml
- questionary/__init__.py
- questionary/form.py
I have had to change the URL used for `prompt_toolkit` in the intersphinx mapping. The problem is described in this PR: prompt-toolkit/python-prompt-toolkit#1485.
Probably best to wait a few days before this PR is merged in case prompt-toolkit/python-prompt-toolkit#1485 is merged quickly. If not, we can merge this and change the URL back once prompt-toolkit/python-prompt-toolkit#1485 is merged.
This PR will make #152 redundant.
> Upgrade Sphinx to v4

- questionary/prompts/common.py
Choices which are selected but also disabled are not returned from a question. This PR changes this behaviour so that any selected choice (even if disabled) is returned.
Closes #187.
Removed check for the choice being disabled.
**Checklist**
> Return selected choices even if they are disabled

- .github/workflows/continous-integration.yml
In the CI, we usually load libraries from the cache. However, this is not done in the `docs` job.
I have added a step to the `docs` job to load cached dependencies.
**Checklist**
> Cache Poetry libraries when building docs

- .github/workflows/continous-integration.yml
- tests/test_question.py
These checks should also be added to the list of required checks
> Remove test preventing CI from completing on Windows with `prompt_toolkit` `2.*`

- questionary/prompts/checkbox.py
- questionary/prompts/select.py
- tests/prompts/test_checkbox.py
- tests/prompts/test_select.py
- tests/utils.py
Emacs key bindings are not supported. Emacs use [Ctrl+N and Ctrl+P](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts) for next and previous.
Most libraries support both Emacs and Vi style (e.g. Python Prompt Toolkit, [Readline](https://web.mit.edu/gnu/doc/html/rlman_1.html))
Add `use_emacs_keys` argument to `select` and `checkbox`.
**Checklist**
> Support Emacs keys (Ctrl+N and Ctrl+P)

- docs/pages/contributors.rst
There should be empty lines before code blocks, otherwise, the documentation is incorrectly rendered.
Added empty lines before two of the code blocks which were missing them.
**Checklist**
> Fix rendering error in the documentation

- .github/workflows/continuous-integration.yml
Fixes a problem introduced in #222.
Some custom entries in the CI matrix do not have an explicit Python version, which does not appear to be supported in later versions of the `setup-python` action.
This should allow #233 to be merged.
I added the Python version to all runs of the CI workflow.
**Checklist**
> Add missing Python version to CI matrix

- examples/advanced_workflow.py
- questionary/prompt.py
- tests/test_examples.py
- tests/test_prompt.py
Adds `print` type to dictionary style prompts. Closes #207.
...
Modified `prompt()` to handle a `print` type that prints a message (with/without optional style).  The `name` field is optional when using `print`. `print` does not return a value and does not add an entry to the returned dict from `prompt()`; it only outputs text.  `print` does work with the `when` keyword so the message can be conditionally printed.
...
**Checklist**
Note: several tests in `tests/prompts/test_select.py` failed with "too many open files".  However, these same tests failed *before* the PR changes.  I'm using a Mac running Catalina 10.15.7. All other tests (including the tests added for this PR) passed.
``` …
```
> Add a `print` question type

- questionary/prompts/checkbox.py
- tests/prompts/test_checkbox.py
There was a static instruction message for selectbox. Thanks to this PR, we now have a way to dynamically change the instruction message thanks to `instruction` argument.
example;
```python
questionary.checkbox(
'Select toppings',
choices=[
"Cheese",
"Tomato",
"Pineapple",
],
instruction="press <enter> to approve"
).ask()
```
...
**Checklist**
> feat: Add dynamic instruction message for checkbox

- docs/pages/types.rst
- questionary/__init__.py
- questionary/prompts/__init__.py
- questionary/prompts/press_any_key_to_continue.py
- tests/prompts/test_press_any_key_to_continue.py
* Previously, there was no convenient way of prompting "Press any key to continue...".
* A similar effect could be achieved using the `confirm` prompt, but it would display yes/no, which may confuse the user.
* Built ontop of #270 so that pre-commit can actually run.
* Implements a "Press any key to continue..." prompt, modeled after the `confirm` prompt.
* We can populate more documentation and stuff if we are happy with this feature.
**Example Use Case**
```
from questionary import press_any_key_to_continue
press_any_key_to_continue().ask()  # Prints " Press any key to continue..."
```
**Checklist**
> Implement 'press any key to continue' prompt

- questionary/constants.py
- questionary/form.py
- questionary/prompt.py
- questionary/question.py
This modules, when the user presses CTRL-C, will print a new-line before and after the message "Cancelled by user ". For some applications, these new-lines might not be desirable.
Removed the printing of new-lines when the KBI message is printed, and instead moved the new-lines to the default message, un-effecting default operation.
**Checklist**
> Move new-lines displayed for the `ctrl+c` message to default constant

- questionary/prompts/select.py
When defining a `Choice` type option with simultaneously setting the `shortcut_key` attribute to `str` type and setting the 
`disabled` attribute to be not `None`, there is an unexpected ability that we can interact with this option using keyboard shortcuts. 
example:
```py
import questionary
from questionary import Choice
options = [
Choice("One", disabled=True),
Choice("Three", shortcut_key="3", disabled=True),
Choice("Two"),
Choice("Four"),
]
questionary.select("Title: ", options, use_shortcuts=True).ask()
```
I cancel the disabled choice binding the key.
**Checklist**
> fix: disabled Choice binding shortcut_key

- questionary/prompts/select.py
Ignore `Seperator` when calculating length of choices in `select` so that we can make full use of the maximum number of keyboard shortcuts.
From
```py
len(choices)
```
To
```py
sum(1 for c in choices if not isinstance(c, Separator))
```
**Checklist**
> Ignore `Seperator` when calculating length of choices in `select`

- .pre-commit-config.yaml
As stated in https://github.com/humitos/mirrors-autoflake/blob/master/README.md, DO NOT USE THIS REPOSITORY. There is an official version now at https://github.com/PyCQA/autoflake/blob/master/.pre-commit-hooks.yaml.
There are some errors when using this deprecated hook under Python 3.12, such as
```
Traceback (most recent call last):
File "/home/fanta/.cache/pre-commit/repoo2mq6vmn/py_env-python3.12/bin/autoflake", line 5, in <module>
from autoflake import main
File "/home/fanta/.cache/pre-commit/repoo2mq6vmn/py_env-python3.12/lib/python3.12/site-packages/autoflake.py", line 32, in <module>
import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils'
```
...
...
**Checklist**
> Update deprecated autoflake hook

- questionary/prompts/common.py
- tests/prompts/test_select.py
Ensures that `Choice.auto_shortcut` is set to `False` whenever `Choice.shortcut_key` is set to a `str` value and vice versa
Closes #340
Implemented the suggested fix in PR #340 to convert `Choices.shortcut_key` to a property with a setter.
**Checklist**
> Change `Choice.shortcut_key` to property with setter

- .pre-commit-config.yaml
This patch resolves lint failure when using Python 3.12.
```
questionary/prompts/common.py:282:24: E713 test for membership should be 'not in'
questionary/prompts/common.py:300:45: E713 test for membership should be 'not in'
```
Flake8 adds Python 3.12 support in 6.1.0.
...
...
**Checklist**
> Update flake8 pre-commit hook to 7.1.0

- poetry.lock
- pyproject.toml
- tests/prompts/test_common.py
Currently one test will fail with latest prompt_toolkit(3.0.43). test_blank_line_fix will throw RuntimeError: no running event loop. By bisecting commit, the culprit is
https://github.com/prompt-toolkit/python-prompt-toolkit/commit/a7759969891c54ea56abfa286524cc301eedaf05. This commit replaces custom `get_event_loop` with `asyncio.get_event_loop`. The former will creator a new loop if `asyncio.get_running_loop` fails while the latter won't. I mimic the changes in the examples to use `asyncio.run` and the test passes. I'm not sure whether more changes are needed.
Closes: https://github.com/tmbo/questionary/issues/344
Use `asyncio.run` to make the test pass.
**Checklist**
> Try to support prompt_toolkit >3.0.37

- pyproject.toml
- setup.cfg
Since questionary uses poetry instead of setuptools, it's better not keep setup.cfg. Mypy can be configured using pyproject.toml.
https://mypy.readthedocs.io/en/stable/config_file.html
**Checklist**
> Remove setup.cfg

- questionary/prompts/common.py
Fixes https://github.com/tmbo/questionary/issues/454
By retrieving the default Prompt Toolkit `Window` instance in a more idiomatic way from a `PromptSession`
instance than using a fixed path through the latter’s `.layout.container` tree structure – which changed w/ release `3.0.52` of Prompt Toolkit, causing the exception described in the linked issue.
**Checklist**
> Use PromptSession.layout.find_all_windows() helper for compatibility w/ prompt-toolkit>=3.0.52

- examples/dependent_selects.py
- questionary/prompt.py
- tests/test_examples.py
Dynamically-generated select choices were broken.
Example:
```python
import questionary
OPTIONS = {
"key1": ["k1v1", "k1v2"], 
"key2": ["k2v1", "k2v2"]
}
questions = [
{
'type': 'select',
'name': 'key',
'message': "Choose a key",
'choices': OPTIONS.keys(),
},
{
'type': 'select',
'name': 'value',
'message': 'Choose a value',
'choices': lambda x: OPTIONS[x['key']],
}
]
questionary.prompt(questions)
```
Results in the following error:
```
? Choose a key key1
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".../venv/lib/python3.10/site-packages/questionary/prompt.py", line 78, in prompt
return unsafe_prompt(questions, answers, patch_stdout, true_color, **kwargs)
File …
```
> Fix dynamically-generated select choices

- questionary/prompts/checkbox.py
Fix default instruction,
The right is `(Use arrow keys to move, <space> to select, <ctrl-a> to toggle, <ctrl-i> to i
nvert, type to filter)`.
> Fix default instruction

- questionary/prompts/checkbox.py
- tests/prompts/test_checkbox.py
Issue #442 
By default, the checkbox prompt in Questionary wraps the cursor from the last item back to the first (and vice versa). In long lists this can be disorienting—overshooting your target immediately jumps you to the other end. There wasn’t a built-in way to disable this “infinite carousel” behavior.
**How did I solve it?**
- Introduced a new `cycle_list: bool` parameter on the `checkbox()` prompt (defaults to True to preserve existing behavior).
- Updated the internal cursor-movement handlers (`move_cursor_down`  / `move_cursor_up`) to check `cycle_list`. When `cycle_list=False`, attempts to move past the first or last item simply do nothing, rather than wrap.
- Added docstring entries for cycle_list.
- Wrote automated tests covering …
> Added cycle_list param and function in Checkbox prompt (issue #442) & Added 2 test cases
